export enum Bundles {
  RHEL8_STANDARD = "wsb-8wthbqzhx",
}

export enum ComputeTypeName {
  VALUE = "VALUE",
  STANDARD = "STANDARD",
  PERFORMANCE = "PERFORMANCE",
  POWER = "POWER",
  GRAPHICS = "GRAPHICS",
  POWERPRO = "POWERPRO",
  GENERALPURPOSE_4XLARGE = "GENERALPURPOSE_4XLARGE",
  GENERALPURPOSE_8XLARGE = "GENERALPURPOSE_8XLARGE",
  GRAPHICSPRO = "GRAPHICSPRO",
  GRAPHICS_G4DN = "GRAPHICS_G4DN",
  GRAPHICSPRO_G4DN = "GRAPHICSPRO_G4DN",
}

export enum RunningMode {
  AUTO_STOP = "AUTO_STOP",
  ALWAYS_ON = "ALWAYS_ON",
  MANUAL = "MANUAL",
}
